-- Supabase SQL Editor에서 전체 실행하세요.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  student_id text unique not null,
  name text not null,
  major text not null,
  year integer not null check (year between 1 and 6),
  role text not null default 'student' check (role in ('student','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.notices enable row level security;

create policy "본인 프로필 조회"
on public.profiles for select
to authenticated
using (auth.uid() = id);

create policy "회원가입 프로필 생성"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

create policy "본인 프로필 수정"
on public.profiles for update
to authenticated
using (auth.uid() = id);

create policy "로그인 사용자는 공지 조회"
on public.notices for select
to authenticated
using (true);

create policy "관리자는 공지 작성"
on public.notices for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'admin'
  )
);

create policy "관리자는 공지 수정"
on public.notices for update
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'admin'
  )
);

create policy "관리자는 공지 삭제"
on public.notices for delete
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'admin'
  )
);

insert into public.notices (title, content)
values
('2학기 수강신청 안내', '2026학년도 2학기 수강신청 일정을 안내합니다. 자세한 일정은 학사 공지를 확인해주세요.'),
('예비군 지원 신청', '학생 예비군 지원 신청 방법과 제출 서류를 안내합니다.'),
('2학기 휴·복학 신청', '2학기 휴학 및 복학 신청 기간과 절차를 확인해주세요.'),
('여름학기 성적 확인', '여름학기 성적 조회 및 이의신청 일정을 안내합니다.'),
('학생 인턴 지원 양식', '학생 인턴 지원서와 개인정보 제공 동의서 양식을 확인해주세요.');
